In [1]:
import pandas as pd

df = pd.read_csv("./source/books.csv")

In [2]:
df.columns

Index(['Title', 'Author', 'Genre', 'Height', 'Publisher'], dtype='str')

In [3]:
df[["Title", "Genre", "Author",]]

                            Title              Genre              Author
0        Fundamentals of Wavelets  signal_processing    Goswami, Jaideva
1                      Data Smart       data_science       Foreman, John
2        God Created the Integers        mathematics    Hawking, Stephen
3               Superfreakonomics          economics     Dubner, Stephen
4                     Orientalism            history        Said, Edward
..                            ...                ...                 ...
206      Structure and Randomness        mathematics        Tao, Terence
207  Image Processing with MATLAB  signal_processing       Eddins, Steve
208                   Animal Farm            fiction      Orwell, George
209                    Idiot, The            fiction  Dostoevsky, Fyodor
210            Christmas Carol, A            fiction    Dickens, Charles

[211 rows x 3 columns]

In [4]:
df.iloc[4][["Title", "Genre"]]

Title    Orientalism
Genre        history
Name: 4, dtype: object

In [5]:
df.head()

,Title,Author,Genre,Height,Publisher
0,Fundamentals of Wavelets,"Goswami, Jaideva",signal_processing,228,Wiley
1,Data Smart,"Foreman, John",data_science,235,Wiley
2,God Created the Integers,"Hawking, Stephen",mathematics,197,Penguin
3,Superfreakonomics,"Dubner, Stephen",economics,179,HarperCollins
4,Orientalism,"Said, Edward",history,197,Penguin

In [6]:
df[(df["Publisher"] == "Penguin") & (df["Genre"] == "history")]

,Title,Author,Genre,Height,Publisher
4,Orientalism,"Said, Edward",history,197,Penguin
14,"Age of Wrath, The","Eraly, Abraham",history,238,Penguin
74,"Last Mughal, The","Dalrymple, William",history,199,Penguin
82,India from Midnight to Milennium,"Tharoor, Shashi",history,198,Penguin

In [7]:
df[(df["Publisher"] == "Penguin") | (df["Publisher"] == "mathematics")]

,Title,Author,Genre,Height,Publisher
2,God Created the Integers,"Hawking, Stephen",mathematics,197,Penguin
4,Orientalism,"Said, Edward",history,197,Penguin
7,"Drunkard's Walk, The","Mlodinow, Leonard",science,197,Penguin
9,How to Think Like Sherlock Holmes,"Konnikova, Maria",psychology,240,Penguin
14,"Age of Wrath, The","Eraly, Abraham",history,238,Penguin
18,"New Machiavelli, The","Wells, H. G.",fiction,180,Penguin
19,Physics & Philosophy,"Heisenberg, Werner",science,197,Penguin
23,"Signal and the Noise, The","Silver, Nate",data_science,233,Penguin
26,"Beautiful and the Damned, The","Deb, Siddhartha",nonfiction,198,Penguin
27,"Outsider, The","Camus, Albert",fiction,198,Penguin
33,"Tao of Physics, The","Capra, Fritjof",science,179,Penguin
39,Return of the Primitive,"Rand, Ayn",philosophy,202,Penguin
41,"Russian Journal, A","Steinbeck, John",nonfiction,196,Penguin
43,Freakonomics,"Dubner, Stephen",economics,197,Penguin
47,Journal of a Novel,"Steinbeck, John",fiction,196,Penguin
48,Once There Was a War,"Steinbeck, John",nonfiction,196,Penguin
49,"Moon is Down, The","Steinbeck, John",fiction,196,Penguin
64,Crime and Punishment,"Dostoevsky, Fyodor",fiction,180,Penguin
67,Sea of Poppies,"Ghosh, Amitav",fiction,197,Penguin
68,"Idea of Justice, The","Sen, Amartya",nonfiction,212,Penguin
69,"Raisin in the Sun, A","Hansberry, Lorraine",fiction,175,Penguin
74,"Last Mughal, The","Dalrymple, William",history,199,Penguin
82,India from Midnight to Milennium,"Tharoor, Shashi",history,198,Penguin
84,"Great Indian Novel, The","Tharoor, Shashi",fiction,198,Penguin
88,"Winter of Our Discontent, The","Steinbeck, John",fiction,196,Penguin
91,Bookless in Baghdad,"Tharoor, Shashi",nonfiction,206,Penguin
94,New Markets & Other Essays,"Drucker, Peter",economics,176,Penguin
95,Electric Universe,"Bodanis, David",science,201,Penguin
97,Burning Bright,"Steinbeck, John",fiction,175,Penguin
99,Doctor in the Nude,"Gordon, Richard",fiction,179,Penguin
100,Down and Out in Paris & London,"Orwell, George",nonfiction,179,Penguin
101,Identity & Violence,"Sen, Amartya",philosophy,219,Penguin
110,We the Living,"Rand, Ayn",fiction,178,Penguin
119,To Sir With Love,Braithwaite,fiction,197,Penguin

In [8]:
df[~df["Publisher"].isin(["Wiley", "HarperCollins"])]

,Title,Author,Genre,Height,Publisher
2,God Created the Integers,"Hawking, Stephen",mathematics,197,Penguin
4,Orientalism,"Said, Edward",history,197,Penguin
5,"Nature of Statistical Learning Theory, The","Vapnik, Vladimir",data_science,230,Springer
6,Integration of the Indian States,"Menon, V P",history,217,Orient Blackswan
7,"Drunkard's Walk, The","Mlodinow, Leonard",science,197,Penguin
...,...,...,...,...,...
206,Structure and Randomness,"Tao, Terence",mathematics,252,NaN
207,Image Processing with MATLAB,"Eddins, Steve",signal_processing,241,NaN
208,Animal Farm,"Orwell, George",fiction,180,NaN
209,"Idiot, The","Dostoevsky, Fyodor",fiction,197,NaN
210,"Christmas Carol, A","Dickens, Charles",fiction,196,NaN

In [13]:
df.loc[df["Title"] == "Idiot, The", "Publisher"] = "Penguin"

In [20]:
#CLEANING DATA
df[~df["Publisher"].isin(["Wiley", "HarperCollins"])]

,Title,Author,Genre,Height,Publisher
2,God Created the Integers,"Hawking, Stephen",mathematics,197,Penguin
4,Orientalism,"Said, Edward",history,197,Penguin
5,"Nature of Statistical Learning Theory, The","Vapnik, Vladimir",data_science,230,Springer
6,Integration of the Indian States,"Menon, V P",history,217,Orient Blackswan
7,"Drunkard's Walk, The","Mlodinow, Leonard",science,197,Penguin
...,...,...,...,...,...
206,Structure and Randomness,"Tao, Terence",mathematics,252,NaN
207,Image Processing with MATLAB,"Eddins, Steve",signal_processing,241,NaN
208,Animal Farm,"Orwell, George",fiction,180,NaN
209,"Idiot, The","Dostoevsky, Fyodor",fiction,197,Penguin
210,"Christmas Carol, A","Dickens, Charles",fiction,196,NaN

In [23]:
cleaned_df = df.dropna()
cleaned_df

,Title,Author,Genre,Height,Publisher
0,Fundamentals of Wavelets,"Goswami, Jaideva",signal_processing,228,Wiley
1,Data Smart,"Foreman, John",data_science,235,Wiley
2,God Created the Integers,"Hawking, Stephen",mathematics,197,Penguin
3,Superfreakonomics,"Dubner, Stephen",economics,179,HarperCollins
4,Orientalism,"Said, Edward",history,197,Penguin
...,...,...,...,...,...
115,Clash of Civilizations and Remaking of the Wor...,"Huntington, Samuel",history,228,Simon&Schuster
116,Uncommon Wisdom,"Capra, Fritjof",nonfiction,197,Fontana
117,One,"Bach, Richard",nonfiction,172,Dell
119,To Sir With Love,Braithwaite,fiction,197,Penguin
209,"Idiot, The","Dostoevsky, Fyodor",fiction,197,Penguin

In [30]:
cleaned_df[cleaned_df["Genre"] == "history"].value_counts()

Title                                                   Author               Genre    Height  Publisher
Orientalism                                             Said, Edward         history  197     Penguin             1
Integration of the Indian States                        Menon, V P           history  217     Orient Blackswan    1
Age of Wrath, The                                       Eraly, Abraham       history  238     Penguin             1
All the President's Men                                 Woodward, Bob        history  177     Random House        1
Scoop!                                                  Nayar, Kuldip        history  216     HarperCollins       1
Last Mughal, The                                        Dalrymple, William   history  199     Penguin             1
India from Midnight to Milennium                        Tharoor, Shashi      history  198     Penguin             1
O Jerusalem!                                            Lapierre, Dominique  history  217     vikas               1
Freedom at Midnight                                     Lapierre, Dominique  history  167     vikas               1
Beyond the Three Seas                                   Dalrymple, William   history  197     Random House        1
Great War for Civilization, The                         Fisk, Robert         history  197     HarperCollins       1
Clash of Civilizations and Remaking of the World Order  Huntington, Samuel   history  228     Simon&Schuster      1
Name: count, dtype: int64

In [32]:
cleaned_df.groupby("Genre").count()

                   Title  Author  Height  Publisher
Genre
computer_science       6       6       6          6
data_science          11      11      11         11
economics              9       9       9          9
fiction               36      36      36         36
history               12      12      12         12
mathematics            3       3       3          3
nonfiction            18      18      18         18
philosophy             7       7       7          7
psychology             1       1       1          1
science                8       8       8          8
signal_processing      2       2       2          2

In [37]:
cleaned_df.groupby("Height").max()

,Title,Author,Genre,Publisher
Height,,,,
160,Ashenden of The British Agent,"Maugham, William S",fiction,Vintage
167,Freedom at Midnight,"Lapierre, Dominique",history,vikas
170,"Story of Philosophy, The","Durant, Will",philosophy,Pocket
171,"Maugham's Collected Short Stories, Vol 3","Maugham, William S",fiction,Vintage
172,Zen & The Art of Motorcycle Maintenance,"Poe, Edgar Allen",philosophy,Vintage
174,Jurassic Park,"Grisham, John",fiction,Random House
175,"Wealth of Nations, The","Steinbeck, John",fiction,Random House
176,"Prisoner of Birth, A","Follett, Ken",fiction,Random House
177,"Veteran, The","Woodward, Bob",history,vikas
178,We the Living,"Rand, Ayn",nonfiction,Random House
179,"Tao of Physics, The","Stroud, Jonathan",science,Rupa
180,"New Machiavelli, The","Wells, H. G.",fiction,Penguin
186,"Artist and the Mathematician, The","Aczel, Amir",science,HighStakes
196,"Winter of Our Discontent, The","Steinbeck, John",nonfiction,Rupa
197,Uncommon Wisdom,"Said, Edward",science,Random House
198,"Trial, The","Vonnegut, Kurt",science,Random House
199,"Last Mughal, The","Dalrymple, William",history,Penguin
201,Electric Universe,"Bodanis, David",science,Penguin
202,Return of the Primitive,"Rand, Ayn",philosophy,Penguin
203,On Education,"Russell, Bertrand",philosophy,Routledge
205,Asami Asami,"Deshpande, P L",fiction,Mauj
206,Bookless in Baghdad,"Tharoor, Shashi",nonfiction,Penguin
209,"Argumentative Indian, The","Sen, Amartya",nonfiction,Picador
212,Mein Kampf,"Sen, Amartya",nonfiction,Rupa
213,Rationality & Freedom,"Sen, Amartya",philosophy,Springer
216,Scoop!,"Nayar, Kuldip",history,HarperCollins
217,"Theory of Everything, The","Menon, V P",science,vikas
219,Identity & Violence,"Sen, Amartya",philosophy,Penguin
221,Maqta-e-Ghalib,"Garg, Sanjay",fiction,Mauj
228,Fundamentals of Wavelets,"Huntington, Samuel",signal_processing,Wiley
230,"Nature of Statistical Learning Theory, The","Vapnik, Vladimir",data_science,Springer
232,Making Software,"Oram, Andy",data_science,O'Reilly
233,"Signal and the Noise, The","Silver, Nate",data_science,Penguin
234,Introduction to Algorithms,"Villani, Cedric",mathematics,MIT Press
235,"Social Choice & Welfare, Vol 39 No. 1",Various,economics,Wiley
236,Statistical Decision Theory',"Pratt, John",data_science,MIT Press
238,"Age of Wrath, The","Eraly, Abraham",history,Penguin
240,Structure & Interpretation of Computer Programs,"Taub, Schilling",psychology,TMH
241,Image Processing & Mathematical Morphology,"Shih, Frank",signal_processing,CRC
242,Textbook of Economic Theory,"Stonier, Alfred",economics,Pearson
248,"Analysis, Vol I","Tao, Terence",mathematics,HBA
255,"Computer Vision, A Modern Approach","Forsyth, David",data_science,Pearson