In [13]:
import pandas as pd

df = pd.read_csv("./source/books.csv")

In [26]:
df.columns

Index(['Title', 'Author', 'Genre', 'Height', 'Publisher'], dtype='str')

In [36]:
df[["Title", "Genre", "Author",]]

                            Title              Genre              Author
0        Fundamentals of Wavelets  signal_processing    Goswami, Jaideva
1                      Data Smart       data_science       Foreman, John
2        God Created the Integers        mathematics    Hawking, Stephen
3               Superfreakonomics          economics     Dubner, Stephen
4                     Orientalism            history        Said, Edward
..                            ...                ...                 ...
206      Structure and Randomness        mathematics        Tao, Terence
207  Image Processing with MATLAB  signal_processing       Eddins, Steve
208                   Animal Farm            fiction      Orwell, George
209                    Idiot, The            fiction  Dostoevsky, Fyodor
210            Christmas Carol, A            fiction    Dickens, Charles

[211 rows x 3 columns]

In [59]:
df.iloc[4][["Title", "Genre"]]

Title    Orientalism
Genre        history
Name: 4, dtype: object

In [60]:
df.head()

,Title,Author,Genre,Height,Publisher
0,Fundamentals of Wavelets,"Goswami, Jaideva",signal_processing,228,Wiley
1,Data Smart,"Foreman, John",data_science,235,Wiley
2,God Created the Integers,"Hawking, Stephen",mathematics,197,Penguin
3,Superfreakonomics,"Dubner, Stephen",economics,179,HarperCollins
4,Orientalism,"Said, Edward",history,197,Penguin

In [71]:
df[(df["Publisher"] == "Penguin") & (df["Genre"] == "history")]

,Title,Author,Genre,Height,Publisher
4,Orientalism,"Said, Edward",history,197,Penguin
14,"Age of Wrath, The","Eraly, Abraham",history,238,Penguin
74,"Last Mughal, The","Dalrymple, William",history,199,Penguin
82,India from Midnight to Milennium,"Tharoor, Shashi",history,198,Penguin

In [72]:
df[(df["Publisher"] == "Penguin") | (df["Publisher"] == "mathematics")]

,Title,Author,Genre,Height,Publisher
2,God Created the Integers,"Hawking, Stephen",mathematics,197,Penguin
4,Orientalism,"Said, Edward",history,197,Penguin
7,"Drunkard's Walk, The","Mlodinow, Leonard",science,197,Penguin
9,How to Think Like Sherlock Holmes,"Konnikova, Maria",psychology,240,Penguin
14,"Age of Wrath, The","Eraly, Abraham",history,238,Penguin
18,"New Machiavelli, The","Wells, H. G.",fiction,180,Penguin
19,Physics & Philosophy,"Heisenberg, Werner",science,197,Penguin
23,"Signal and the Noise, The","Silver, Nate",data_science,233,Penguin
26,"Beautiful and the Damned, The","Deb, Siddhartha",nonfiction,198,Penguin
27,"Outsider, The","Camus, Albert",fiction,198,Penguin
33,"Tao of Physics, The","Capra, Fritjof",science,179,Penguin
39,Return of the Primitive,"Rand, Ayn",philosophy,202,Penguin
41,"Russian Journal, A","Steinbeck, John",nonfiction,196,Penguin
43,Freakonomics,"Dubner, Stephen",economics,197,Penguin
47,Journal of a Novel,"Steinbeck, John",fiction,196,Penguin
48,Once There Was a War,"Steinbeck, John",nonfiction,196,Penguin
49,"Moon is Down, The","Steinbeck, John",fiction,196,Penguin
64,Crime and Punishment,"Dostoevsky, Fyodor",fiction,180,Penguin
67,Sea of Poppies,"Ghosh, Amitav",fiction,197,Penguin
68,"Idea of Justice, The","Sen, Amartya",nonfiction,212,Penguin
69,"Raisin in the Sun, A","Hansberry, Lorraine",fiction,175,Penguin
74,"Last Mughal, The","Dalrymple, William",history,199,Penguin
82,India from Midnight to Milennium,"Tharoor, Shashi",history,198,Penguin
84,"Great Indian Novel, The","Tharoor, Shashi",fiction,198,Penguin
88,"Winter of Our Discontent, The","Steinbeck, John",fiction,196,Penguin
91,Bookless in Baghdad,"Tharoor, Shashi",nonfiction,206,Penguin
94,New Markets & Other Essays,"Drucker, Peter",economics,176,Penguin
95,Electric Universe,"Bodanis, David",science,201,Penguin
97,Burning Bright,"Steinbeck, John",fiction,175,Penguin
99,Doctor in the Nude,"Gordon, Richard",fiction,179,Penguin
100,Down and Out in Paris & London,"Orwell, George",nonfiction,179,Penguin
101,Identity & Violence,"Sen, Amartya",philosophy,219,Penguin
110,We the Living,"Rand, Ayn",fiction,178,Penguin
119,To Sir With Love,Braithwaite,fiction,197,Penguin

In [77]:
df[~df["Publisher"].isin(["Wiley", "HarperCollins"])]

,Title,Author,Genre,Height,Publisher
2,God Created the Integers,"Hawking, Stephen",mathematics,197,Penguin
4,Orientalism,"Said, Edward",history,197,Penguin
5,"Nature of Statistical Learning Theory, The","Vapnik, Vladimir",data_science,230,Springer
6,Integration of the Indian States,"Menon, V P",history,217,Orient Blackswan
7,"Drunkard's Walk, The","Mlodinow, Leonard",science,197,Penguin
...,...,...,...,...,...
206,Structure and Randomness,"Tao, Terence",mathematics,252,NaN
207,Image Processing with MATLAB,"Eddins, Steve",signal_processing,241,NaN
208,Animal Farm,"Orwell, George",fiction,180,NaN
209,"Idiot, The","Dostoevsky, Fyodor",fiction,197,NaN
210,"Christmas Carol, A","Dickens, Charles",fiction,196,NaN

In [78]:
df.loc[df["Genre"] == "mathematics"]

,Title,Author,Genre,Height,Publisher
2,God Created the Integers,"Hawking, Stephen",mathematics,197,Penguin
12,Birth of a Theorem,"Villani, Cedric",mathematics,234,Bodley Head
21,"Analysis, Vol I","Tao, Terence",mathematics,248,HBA
182,Men of Mathematics,"Bell, E T",mathematics,217,NaN
206,Structure and Randomness,"Tao, Terence",mathematics,252,NaN